<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GeoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $divisions = [
            ['id' => 1, 'name' => 'Chattogram'],
            ['id' => 2, 'name' => 'Rajshahi'],
            ['id' => 3, 'name' => 'Khulna'],
            ['id' => 4, 'name' => 'Barisal'],
            ['id' => 5, 'name' => 'Sylhet'],
            ['id' => 6, 'name' => 'Dhaka'],
            ['id' => 7, 'name' => 'Rangpur'],
            ['id' => 8, 'name' => 'Mymensingh'],
        ];

        DB::table('divisions')->insert($divisions);

        $districts = [
            ['id' => 1, 'division_id' => 1, 'name' => 'Cumilla'],
            ['id' => 2, 'division_id' => 1, 'name' => 'Feni'],
            ['id' => 3, 'division_id' => 1, 'name' => 'Brahmanbaria'],
            ['id' => 4, 'division_id' => 1, 'name' => 'Rangamati'],
            ['id' => 5, 'division_id' => 1, 'name' => 'Noakhali'],
            ['id' => 6, 'division_id' => 1, 'name' => 'Chandpur'],
            ['id' => 7, 'division_id' => 1, 'name' => 'Lakshmipur'],
            ['id' => 8, 'division_id' => 1, 'name' => 'Chattogram'],
            ['id' => 9, 'division_id' => 1, 'name' => "Cox's Bazar"],
            ['id' => 10, 'division_id' => 1, 'name' => 'Khagrachari'],
            ['id' => 11, 'division_id' => 1, 'name' => 'Bandarban'],
            ['id' => 12, 'division_id' => 2, 'name' => 'Sirajganj'],
            ['id' => 13, 'division_id' => 2, 'name' => 'Pabna'],
            ['id' => 14, 'division_id' => 2, 'name' => 'Bogura'],
            ['id' => 15, 'division_id' => 2, 'name' => 'Rajshahi'],
            ['id' => 16, 'division_id' => 2, 'name' => 'Natore'],
            ['id' => 17, 'division_id' => 2, 'name' => 'Joypurhat'],
            ['id' => 18, 'division_id' => 2, 'name' => 'Chapainawabganj'],
            ['id' => 19, 'division_id' => 2, 'name' => 'Naogaon'],
            ['id' => 20, 'division_id' => 3, 'name' => 'Jashore'],
            ['id' => 21, 'division_id' => 3, 'name' => 'Satkhira'],
            ['id' => 22, 'division_id' => 3, 'name' => 'Meherpur'],
            ['id' => 23, 'division_id' => 3, 'name' => 'Narail'],
            ['id' => 24, 'division_id' => 3, 'name' => 'Chuadanga'],
            ['id' => 25, 'division_id' => 3, 'name' => 'Kushtia'],
            ['id' => 26, 'division_id' => 3, 'name' => 'Magura'],
            ['id' => 27, 'division_id' => 3, 'name' => 'Khulna'],
            ['id' => 28, 'division_id' => 3, 'name' => 'Bagerhat'],
            ['id' => 29, 'division_id' => 3, 'name' => 'Jhenaidah'],
            ['id' => 30, 'division_id' => 4, 'name' => 'Jhalokati'],
            ['id' => 31, 'division_id' => 4, 'name' => 'Patuakhali'],
            ['id' => 32, 'division_id' => 4, 'name' => 'Pirojpur'],
            ['id' => 33, 'division_id' => 4, 'name' => 'Barisal'],
            ['id' => 34, 'division_id' => 4, 'name' => 'Bhola'],
            ['id' => 35, 'division_id' => 4, 'name' => 'Barguna'],
            ['id' => 36, 'division_id' => 5, 'name' => 'Sylhet'],
            ['id' => 37, 'division_id' => 5, 'name' => 'Moulvibazar'],
            ['id' => 38, 'division_id' => 5, 'name' => 'Habiganj'],
            ['id' => 39, 'division_id' => 5, 'name' => 'Sunamganj'],
            ['id' => 40, 'division_id' => 6, 'name' => 'Narsingdi'],
            ['id' => 41, 'division_id' => 6, 'name' => 'Gazipur'],
            ['id' => 42, 'division_id' => 6, 'name' => 'Shariatpur'],
            ['id' => 43, 'division_id' => 6, 'name' => 'Narayanganj'],
            ['id' => 44, 'division_id' => 6, 'name' => 'Tangail'],
            ['id' => 45, 'division_id' => 6, 'name' => 'Kishoreganj'],
            ['id' => 46, 'division_id' => 6, 'name' => 'Manikganj'],
            ['id' => 47, 'division_id' => 6, 'name' => 'Dhaka'],
            ['id' => 48, 'division_id' => 6, 'name' => 'Munshiganj'],
            ['id' => 49, 'division_id' => 6, 'name' => 'Rajbari'],
            ['id' => 50, 'division_id' => 6, 'name' => 'Madaripur'],
            ['id' => 51, 'division_id' => 6, 'name' => 'Gopalganj'],
            ['id' => 52, 'division_id' => 6, 'name' => 'Faridpur'],
            ['id' => 53, 'division_id' => 7, 'name' => 'Panchagarh'],
            ['id' => 54, 'division_id' => 7, 'name' => 'Dinajpur'],
            ['id' => 55, 'division_id' => 7, 'name' => 'Lalmonirhat'],
            ['id' => 56, 'division_id' => 7, 'name' => 'Nilphamari'],
            ['id' => 57, 'division_id' => 7, 'name' => 'Gaibandha'],
            ['id' => 58, 'division_id' => 7, 'name' => 'Thakurgaon'],
            ['id' => 59, 'division_id' => 7, 'name' => 'Rangpur'],
            ['id' => 60, 'division_id' => 7, 'name' => 'Kurigram'],
            ['id' => 61, 'division_id' => 8, 'name' => 'Sherpur'],
            ['id' => 62, 'division_id' => 8, 'name' => 'Mymensingh'],
            ['id' => 63, 'division_id' => 8, 'name' => 'Jamalpur'],
            ['id' => 64, 'division_id' => 8, 'name' => 'Netrokona'],
        ];
        DB::table('districts')->insert($districts);

        $upazilas = [
            ['district_id' => 1, 'name' => 'Debidwar'],
            ['district_id' => 1, 'name' => 'Barura'],
            ['district_id' => 1, 'name' => 'Brahmanpara'],
            ['district_id' => 1, 'name' => 'Chandina'],
            ['district_id' => 1, 'name' => 'Chauddagram'],
            ['district_id' => 1, 'name' => 'Daudkandi'],
            [' district_id' => 1, 'name' => 'Homna'],
            ['district_id' => 1, 'name' => 'Laksam'],
            [' district_id' => 1, 'name' => 'Muradnagar'],
            ['district_id' => 1, 'name' => 'Nangalkot'],
            ['district_id' => 1, 'name' => 'Cumilla Sadar'],
            ['district_id' => 1, 'name' => 'Meghna'],
            ['district_id' => 1, 'name' => 'Monohargonj'],
            ['district_id' => 1, 'name' => 'Cumilla Sadar Dakshin'],
            ['district_id' => 1, 'name' => 'Titas'],
            ['district_id' => 1, 'name' => 'Burichang'],
            ['district_id' => 1, 'name' => 'Lalmai'],
            ['district_id' => 2, 'name' => 'Chhagalnaiya'],
            ['district_id' => 2, 'name' => 'Feni Sadar'],
            ['district_id' => 2, 'name' => 'Sonagazi'],
            ['district_id' => 2, 'name' => 'Fulgazi'],
            ['district_id' => 2, 'name' => 'Parshuram'],
            ['district_id' => 2, 'name' => 'Daganbhuiyan'],
            ['district_id' => 3, 'name' => 'Brahmanbaria Sadar'],
            ['district_id' => 3, 'name' => 'Kasba'],
            ['district_id' => 3, 'name' => 'Nasirnagar'],
            ['district_id' => 3, 'name' => 'Sarail'],
            ['district_id' => 3, 'name' => 'Ashuganj'],
            ['district_id' => 3, 'name' => 'Akhaura'],
            ['district_id' => 3, 'name' => 'Nabinagar'],
            ['district_id' => 3, 'name' => 'Bancharampur'],
            ['district_id' => 3, 'name' => 'Bijoynagar'],
            ['district_id' => 4, 'name' => 'Rangamati Sadar'],
            ['district_id' => 4, 'name' => 'Kaptai'],
            ['district_id' => 4, 'name' => 'Kawkhali'],
            ['district_id' => 4, 'name' => 'Baghaichari'],
            ['district_id' => 4, 'name' => 'Barkal'],
            ['district_id' => 4, 'name' => 'Langadu'],
            ['district_id' => 4, 'name' => 'Rajasthali'],
            ['district_id' => 4, 'name' => 'Belaichari'],
            ['district_id' => 4, 'name' => 'Juraichari'],
            ['district_id' => 4, 'name' => 'Naniarchar'],
            ['district_id' => 5, 'name' => 'Noakhali Sadar'],
            ['district_id' => 5, 'name' => 'Companiganj'],
            ['district_id' => 5, 'name' => 'Begumganj'],
            ['district_id' => 5, 'name' => 'Hatia'],
            ['district_id' => 5, 'name' => 'Subarnachar'],
            ['district_id' => 5, 'name' => 'Kabirhat'],
            ['district_id' => 5, 'name' => 'Senbagh'],
            ['district_id' => 5, 'name' => 'Chatkhil'],
            ['district_id' => 5, 'name' => 'Sonaimuri'],
            ['district_id' => 6, 'name' => 'Haimchar'],
            ['district_id' => 6, 'name' => 'Kachua'],
            ['district_id' => 6, 'name' => 'Shahrasti'],
            ['district_id' => 6, 'name' => 'Chandpur Sadar'],
            ['district_id' => 6, 'name' => 'Matlab South'],
            ['district_id' => 6, 'name' => 'Haziganj'],
            ['district_id' => 6, 'name' => 'Matlab North'],
            ['district_id' => 6, 'name' => 'Faridganj'],
            ['district_id' => 7, 'name' => 'Lakshmipur Sadar'],
            ['district_id' => 7, 'name' => 'Kamalnagar'],
            ['district_id' => 7, 'name' => 'Raipur'],
            ['district_id' => 7, 'name' => 'Ramgati'],
            ['district_id' => 7, 'name' => 'Ramganj'],
            ['district_id' => 8, 'name' => 'Rangunia'],
            ['district_id' => 8, 'name' => 'Sitakunda'],
            ['district_id' => 8, 'name' => 'Mirsharai'],
            ['district_id' => 8, 'name' => 'Patiya'],
            ['district_id' => 8, 'name' => 'Sandwip'],
            ['district_id' => 8, 'name' => 'Banshkhali'],
            ['district_id' => 8, 'name' => 'Boalkhali'],
            ['district_id' => 8, 'name' => 'Anwara'],
            ['district_id' => 8, 'name' => 'Chandanaish'],
            ['district_id' => 8, 'name' => 'Satkania'],
            ['district_id' => 8, 'name' => 'Lohagara'],
            ['district_id' => 8, 'name' => 'Hathazari'],
            ['district_id' => 8, 'name' => 'Fatikchhari'],
            ['district_id' => 8, 'name' => 'Raozan'],
            ['district_id' => 8, 'name' => 'Karnafuli'],
            ['district_id' => 9, 'name' => "Cox's Bazar Sadar"],
            ['district_id' => 9, 'name' => 'Chakaria'],
            ['district_id' => 9, 'name' => 'Kutubdia'],
            ['district_id' => 9, 'name' => 'Ukhiya'],
            ['district_id' => 9, 'name' => 'Moheshkhali'],
            ['district_id' => 9, 'name' => 'Pekua'],
            ['district_id' => 9, 'name' => 'Ramu'],
            ['district_id' => 9, 'name' => 'Teknaf'],
            ['district_id' => 10, 'name' => 'Khagrachari Sadar'],
            ['district_id' => 10, 'name' => 'Dighinala'],
            ['district_id' => 10, 'name' => 'Panchhari'],
            ['district_id' => 10, 'name' => 'Luxmichari'],
            ['district_id' => 10, 'name' => 'Mahalchari'],
            ['district_id' => 10, 'name' => 'Manikchari'],
            ['district_id' => 10, 'name' => 'Ramgarh'],
            ['district_id' => 10, 'name' => 'Matiranga'],
            ['district_id' => 10, 'name' => 'Guimara'],
            ['district_id' => 11, 'name' => 'Bandarban Sadar'],
            ['district_id' => 11, 'name' => 'Alikadam'],
            ['district_id' => 11, 'name' => 'Naikhongchhari'],
            ['district_id' => 11, 'name' => 'Rowangchhari'],
            ['district_id' => 11, 'name' => 'Lama'],
            ['district_id' => 11, 'name' => 'Ruma'],
            ['district_id' => 11, 'name' => 'Thanchi'],
            ['district_id' => 12, 'name' => 'Belkuchi'],
            ['district_id' => 12, 'name' => 'Chauhali'],
            ['district_id' => 12, 'name' => 'Kamarkhanda'],
            ['district_id' => 12, 'name' => 'Kazipur'],
            ['district_id' => 12, 'name' => 'Raiganj'],
            ['district_id' => 12, 'name' => 'Shahjadpur'],
            ['district_id' => 12, 'name' => 'Sirajganj Sadar'],
            ['district_id' => 12, 'name' => 'Tarash'],
            ['district_id' => 12, 'name' => 'Ullapara'],
            ['district_id' => 13, 'name' => 'Sujanagar'],
            ['district_id' => 13, 'name' => 'Ishwardi'],
            ['district_id' => 13, 'name' => 'Bhangura'],
            ['district_id' => 13, 'name' => 'Pabna Sadar'],
            ['district_id' => 13, 'name' => 'Bera'],
            ['district_id' => 13, 'name' => 'Atghoria'],
            ['district_id' => 13, 'name' => 'Chatmohar'],
            ['district_id' => 13, 'name' => 'Santhia'],
            ['district_id' => 13, 'name' => 'Faridpur'],
            ['district_id' => 14, 'name' => 'Kahaloo'],
            ['district_id' => 14, 'name' => 'Bogra Sadar'],
            ['district_id' => 14, 'name' => 'Sariakandi'],
            ['district_id' => 14, 'name' => 'Shajahanpur'],
            ['district_id' => 14, 'name' => 'Dupchanchia'],
            ['district_id' => 14, 'name' => 'Adamdighi'],
            ['district_id' => 14, 'name' => 'Nandigram'],
            ['district_id' => 14, 'name' => 'Sonatala'],
            ['district_id' => 14, 'name' => 'Dhunat'],
            ['district_id' => 14, 'name' => 'Gabtali'],
            ['district_id' => 14, 'name' => 'Sherpur'],
            ['district_id' => 14, 'name' => 'Shibganj'],
            ['district_id' => 15, 'name' => 'Paba'],
            ['district_id' => 15, 'name' => 'Durgapur'],
            ['district_id' => 15, 'name' => 'Mohanpur'],
            ['district_id' => 15, 'name' => 'Charghat'],
            ['district_id' => 15, 'name' => 'Puthia'],
            ['district_id' => 15, 'name' => 'Bagha'],
            ['district_id' => 15, 'name' => 'Godagari'],
            ['district_id' => 15, 'name' => 'Tanore'],
            ['district_id' => 15, 'name' => 'Bagmara'],
            ['district_id' => 16, 'name' => 'Natore Sadar'],
            ['district_id' => 16, 'name' => 'Singra'],
            ['district_id' => 16, 'name' => 'Baraigram'],
            ['district_id' => 16, 'name' => 'Bagatipara'],
            ['district_id' => 16, 'name' => 'Lalpur'],
            ['district_id' => 16, 'name' => 'Gurudaspur'],
            ['district_id' => 16, 'name' => 'Naldanga'],
            ['district_id' => 17, 'name' => 'Akkelpur'],
            ['district_id' => 17, 'name' => 'Kalai'],
            ['district_id' => 17, 'name' => 'Khetlal'],
            ['district_id' => 17, 'name' => 'Panchbibi'],
            ['district_id' => 17, 'name' => 'Joypurhat Sadar'],
            ['district_id' => 18, 'name' => 'Nawabganj Sadar'],
            ['district_id' => 18, 'name' => 'Gomastapur'],
            ['district_id' => 18, 'name' => 'Nachole'],
            ['district_id' => 18, 'name' => 'Bholahat'],
            ['district_id' => 18, 'name' => 'Shibganj'],
            ['district_id' => 19, 'name' => 'Mohadevpur'],
            ['district_id' => 19, 'name' => 'Badalgachi'],
            ['district_id' => 19, 'name' => 'Patnitala'],
            ['district_id' => 19, 'name' => 'Dhamoirhat'],
            ['district_id' => 19, 'name' => 'Niamatpur'],
            ['district_id' => 19, 'name' => 'Manda'],
            ['district_id' => 19, 'name' => 'Atrai'],
            ['district_id' => 19, 'name' => 'Raninagar'],
            ['district_id' => 19, 'name' => 'Naogaon Sadar'],
            ['district_id' => 19, 'name' => 'Porsha'],
            ['district_id' => 19, 'name' => 'Sapahar'],
            ['district_id' => 20, 'name' => 'Manirampur'],
            ['district_id' => 20, 'name' => 'Abhaynagar'],
            ['district_id' => 20, 'name' => 'Bagherpara'],
            ['district_id' => 20, 'name' => 'Chowgacha'],
            ['district_id' => 20, 'name' => 'Jhikargacha'],
            ['district_id' => 20, 'name' => 'Keshabpur'],
            ['district_id' => 20, 'name' => 'Jashore Sadar'],
            ['district_id' => 20, 'name' => 'Sharsha'],
            ['district_id' => 21, 'name' => 'Assasuni'],
            ['district_id' => 21, 'name' => 'Debhata'],
            ['district_id' => 21, 'name' => 'Kalaroa'],
            ['district_id' => 21, 'name' => 'Satkhira Sadar'],
            ['district_id' => 21, 'name' => 'Shyamnagar'],
            ['district_id' => 21, 'name' => 'Tala'],
            ['district_id' => 21, 'name' => 'Kaliganj'],
            ['district_id' => 22, 'name' => 'Mujibnagar'],
            ['district_id' => 22, 'name' => 'Meherpur Sadar'],
            ['district_id' => 22, 'name' => 'Gangni'],
            ['district_id' => 23, 'name' => 'Narail Sadar'],
            ['district_id' => 23, 'name' => 'Lohagara'],
            ['district_id' => 23, 'name' => 'Kalia'],
            ['district_id' => 24, 'name' => 'Chuadanga Sadar'],
            ['district_id' => 24, 'name' => 'Alamdanga'],
            ['district_id' => 24, 'name' => 'Damurhuda'],
            ['district_id' => 24, 'name' => 'Jibannagar'],
            ['district_id' => 25, 'name' => 'Kushtia Sadar'],
            ['district_id' => 25, 'name' => 'Kumarkhali'],
            ['district_id' => 25, 'name' => 'Khoksa'],
            ['district_id' => 25, 'name' => 'Mirpur'],
            ['district_id' => 25, 'name' => 'Daulatpur'],
            ['district_id' => 25, 'name' => 'Bheramara'],
            ['district_id' => 26, 'name' => 'Shalikha'],
            ['district_id' => 26, 'name' => 'Sreepur'],
            ['district_id' => 26, 'name' => 'Magura Sadar'],
            ['district_id' => 26, 'name' => 'Mohammadpur'],
            ['district_id' => 27, 'name' => 'Paikgacha'],
            ['district_id' => 27, 'name' => 'Phultala'],
            ['district_id' => 27, 'name' => 'Dighalia'],
            ['district_id' => 27, 'name' => 'Rupsha'],
            ['district_id' => 27, 'name' => 'Terokhada'],
            ['district_id' => 27, 'name' => 'Dumuria'],
            ['district_id' => 27, 'name' => 'Batiaghata'],
            ['district_id' => 27, 'name' => 'Dakop'],
            ['district_id' => 27, 'name' => 'Koyra'],
            ['district_id' => 28, 'name' => 'Fakirhat'],
            ['district_id' => 28, 'name' => 'Bagerhat Sadar'],
            ['district_id' => 28, 'name' => 'Mollahat'],
            ['district_id' => 28, 'name' => 'Sarankhola'],
            ['district_id' => 28, 'name' => 'Rampal'],
            ['district_id' => 28, 'name' => 'Morrelganj'],
            ['district_id' => 28, 'name' => 'Kachua'],
            ['district_id' => 28, 'name' => 'Mongla'],
            ['district_id' => 28, 'name' => 'Chitalmari'],
            ['district_id' => 29, 'name' => 'Jhenaidah Sadar'],
            ['district_id' => 29, 'name' => 'Shailkupa'],
            ['district_id' => 29, 'name' => 'Harinakundu'],
            ['district_id' => 29, 'name' => 'Kaliganj'],
            ['district_id' => 29, 'name' => 'Kotchandpur'],
            ['district_id' => 29, 'name' => 'Maheshpur'],
            ['district_id' => 30, 'name' => 'Jhalakathi Sadar'],
            ['district_id' => 30, 'name' => 'Kathalia'],
            ['district_id' => 30, 'name' => 'Nalchity'],
            ['district_id' => 30, 'name' => 'Rajapur'],
            ['district_id' => 31, 'name' => 'Bauphal'],
            ['district_id' => 31, 'name' => 'Patuakhali Sadar'],
            ['district_id' => 31, 'name' => 'Dumki'],
            ['district_id' => 31, 'name' => 'Dashmina'],
            ['district_id' => 31, 'name' => 'Kalapara'],
            ['district_id' => 31, 'name' => 'Mirzaganj'],
            ['district_id' => 31, 'name' => 'Galachipa'],
            ['district_id' => 31, 'name' => 'Rangabali'],
            ['district_id' => 32, 'name' => 'Pirojpur Sadar'],
            ['district_id' => 32, 'name' => 'Nazirpur'],
            ['district_id' => 32, 'name' => 'Kawkhali'],
            ['district_id' => 32, 'name' => 'Zianagar'],
            ['district_id' => 32, 'name' => 'Bhandaria'],
            ['district_id' => 32, 'name' => 'Mathbaria'],
            ['district_id' => 32, 'name' => 'Nesarabad(Swarupkati)'],
            ['district_id' => 33, 'name' => 'Barisal Sadar'],
            ['district_id' => 33, 'name' => 'Bakerganj'],
            ['district_id' => 33, 'name' => 'Babuganj'],
            ['district_id' => 33, 'name' => 'Wazirpur'],
            ['district_id' => 33, 'name' => 'Banaripara'],
            ['district_id' => 33, 'name' => 'Gournadi'],
            ['district_id' => 33, 'name' => 'Agailjhara'],
            ['district_id' => 33, 'name' => 'Mehendiganj'],
            ['district_id' => 33, 'name' => 'Muladi'],
            ['district_id' => 33, 'name' => 'Hizla'],
            ['district_id' => 34, 'name' => 'Bhola Sadar'],
            ['district_id' => 34, 'name' => 'Borhanuddin'],
            ['district_id' => 34, 'name' => 'Char Fasson'],
            ['district_id' => 34, 'name' => 'Daulatkhan'],
            ['district_id' => 34, 'name' => 'Manpura'],
            ['district_id' => 34, 'name' => 'Tazumuddin'],
            ['district_id' => 34, 'name' => 'Lalmohan'],
            ['district_id' => 35, 'name' => 'Amtali'],
            ['district_id' => 35, 'name' => 'Barguna Sadar'],
            ['district_id' => 35, 'name' => 'Betagi'],
            ['district_id' => 35, 'name' => 'Bamna'],
            ['district_id' => 35, 'name' => 'Patharghata'],
            ['district_id' => 35, 'name' => 'Taltali'],
            ['district_id' => 36, 'name' => 'Balaganj'],
            ['district_id' => 36, 'name' => 'Beanibazar'],
            ['district_id' => 36, 'name' => 'Bishwanath'],
            ['district_id' => 36, 'name' => 'Companiganj'],
            ['district_id' => 36, 'name' => 'Fenchuganj'],
            ['district_id' => 36, 'name' => 'Golapganj'],
            ['district_id' => 36, 'name' => 'Gowainghat'],
            ['district_id' => 36, 'name' => 'Jaintiapur'],
            ['district_id' => 36, 'name' => 'Kanaighat'],
            ['district_id' => 36, 'name' => 'Sylhet Sadar'],
            ['district_id' => 36, 'name' => 'Zakiganj'],
            ['district_id' => 36, 'name' => 'Dakshin Surma'],
            ['district_id' => 36, 'name' => 'Osmaninagar'],
            ['district_id' => 37, 'name' => 'Barlekha'],
            ['district_id' => 37, 'name' => 'Kamalganj'],
            ['district_id' => 37, 'name' => 'Kulaura'],
            ['district_id' => 37, 'name' => 'Moulvibazar Sadar'],
            ['district_id' => 37, 'name' => 'Rajnagar'],
            ['district_id' => 37, 'name' => 'Sreemangal'],
            ['district_id' => 37, 'name' => 'Juri'],
            ['district_id' => 38, 'name' => 'Nabiganj'],
            ['district_id' => 38, 'name' => 'Bahubal'],
            ['district_id' => 38, 'name' => 'Ajmiriganj'],
            ['district_id' => 38, 'name' => 'Baniachong'],
            ['district_id' => 38, 'name' => 'Lakhai'],
            ['district_id' => 38, 'name' => 'Chunarughat'],
            ['district_id' => 38, 'name' => 'Habiganj Sadar'],
            ['district_id' => 38, 'name' => 'Madhabpur'],
            ['district_id' => 39, 'name' => 'Sunamganj Sadar'],
            ['district_id' => 39, 'name' => 'South Sunamganj'],
            ['district_id' => 39, 'name' => 'Bishwamvarpur'],
            ['district_id' => 39, 'name' => 'Chhatak'],
            ['district_id' => 39, 'name' => 'Jagannathpur'],
            ['district_id' => 39, 'name' => 'Dowarabazar'],
            ['district_id' => 39, 'name' => 'Tahirpur'],
            ['district_id' => 39, 'name' => 'Dharmapasha'],
            ['district_id' => 39, 'name' => 'Jamalganj'],
            ['district_id' => 39, 'name' => 'Sullah'],
            ['district_id' => 39, 'name' => 'Derai'],
            ['district_id' => 40, 'name' => 'Belabo'],
            ['district_id' => 40, 'name' => 'Monohardi'],
            ['district_id' => 40, 'name' => 'Narsingdi Sadar'],
            ['district_id' => 40, 'name' => 'Palash'],
            ['district_id' => 40, 'name' => 'Raipura'],
            ['district_id' => 40, 'name' => 'Shibpur'],
            ['district_id' => 41, 'name' => 'Kaliganj'],
            ['district_id' => 41, 'name' => 'Kaliakair'],
            ['district_id' => 41, 'name' => 'Kapasia'],
            ['district_id' => 41, 'name' => 'Gazipur Sadar'],
            ['district_id' => 41, 'name' => 'Sreepur'],
            ['district_id' => 42, 'name' => 'Shariatpur Sadar'],
            ['district_id' => 42, 'name' => 'Naria'],
            ['district_id' => 42, 'name' => 'Zajira'],
            ['district_id' => 42, 'name' => 'Gosairhat'],
            ['district_id' => 42, 'name' => 'Bhedarganj'],
            ['district_id' => 42, 'name' => 'Damudya'],
            ['district_id' => 43, 'name' => 'Araihazar'],
            ['district_id' => 43, 'name' => 'Bandar'],
            ['district_id' => 43, 'name' => 'Narayanganj Sadar'],
            ['district_id' => 43, 'name' => 'Rupganj'],
            ['district_id' => 43, 'name' => 'Sonargaon'],
            ['district_id' => 44, 'name' => 'Basail'],
            ['district_id' => 44, 'name' => 'Bhuapur'],
            ['district_id' => 44, 'name' => 'Delduar'],
            ['district_id' => 44, 'name' => 'Ghatail'],
            ['district_id' => 44, 'name' => 'Gopalpur'],
            ['district_id' => 44, 'name' => 'Madhupur'],
            ['district_id' => 44, 'name' => 'Mirzapur'],
            ['district_id' => 44, 'name' => 'Nagarpur'],
            ['district_id' => 44, 'name' => 'Sakhipur'],
            ['district_id' => 44, 'name' => 'Tangail Sadar'],
            ['district_id' => 44, 'name' => 'Kalihati'],
            ['district_id' => 44, 'name' => 'Dhanbari'],
            ['district_id' => 45, 'name' => 'Itna'],
            ['district_id' => 45, 'name' => 'Katiadi'],
            ['district_id' => 45, 'name' => 'Bhairab'],
            ['district_id' => 45, 'name' => 'Tarail'],
            ['district_id' => 45, 'name' => 'Hossainpur'],
            ['district_id' => 45, 'name' => 'Pakundia'],
            ['district_id' => 45, 'name' => 'Kuliarchar'],
            ['district_id' => 45, 'name' => 'Kishoreganj Sadar'],
            ['district_id' => 45, 'name' => 'Karimganj'],
            ['district_id' => 45, 'name' => 'Bajitpur'],
            ['district_id' => 45, 'name' => 'Austagram'],
            ['district_id' => 45, 'name' => 'Mithamoin'],
            ['district_id' => 45, 'name' => 'Nikli'],
            ['district_id' => 46, 'name' => 'Harirampur'],
            ['district_id' => 46, 'name' => 'Saturia'],
            ['district_id' => 46, 'name' => 'Manikganj Sadar'],
            ['district_id' => 46, 'name' => 'Ghior'],
            ['district_id' => 46, 'name' => 'Shivalaya'],
            ['district_id' => 46, 'name' => 'Doulatpur'],
            ['district_id' => 46, 'name' => 'Singair'],
            ['district_id' => 47, 'name' => 'Savar'],
            ['district_id' => 47, 'name' => 'Dhamrai'],
            ['district_id' => 47, 'name' => 'Keraniganj'],
            ['district_id' => 47, 'name' => 'Nawabganj'],
            ['district_id' => 47, 'name' => 'Dohar'],
            ['district_id' => 48, 'name' => 'Munshiganj Sadar'],
            ['district_id' => 48, 'name' => 'Sreenagar'],
            ['district_id' => 48, 'name' => 'Sirajdikhan'],
            ['district_id' => 48, 'name' => 'Louhajanj'],
            ['district_id' => 48, 'name' => 'Gazaria'],
            ['district_id' => 48, 'name' => 'Tongibari'],
            ['district_id' => 49, 'name' => 'Rajbari Sadar'],
            ['district_id' => 49, 'name' => 'Goalanda'],
            ['district_id' => 49, 'name' => 'Pangsa'],
            ['district_id' => 49, 'name' => 'Baliakandi'],
            ['district_id' => 49, 'name' => 'Kalukhali'],
            ['district_id' => 50, 'name' => 'Madaripur Sadar'],
            ['district_id' => 50, 'name' => 'Shibchar'],
            ['district_id' => 50, 'name' => 'Kalkini'],
            ['district_id' => 50, 'name' => 'Rajoir'],
            ['district_id' => 51, 'name' => 'Gopalganj Sadar'],
            ['district_id' => 51, 'name' => 'Kashiani'],
            ['district_id' => 51, 'name' => 'Tungipara'],
            ['district_id' => 51, 'name' => 'Kotalipara'],
            ['district_id' => 51, 'name' => 'Muksudpur'],
            ['district_id' => 52, 'name' => 'Faridpur Sadar'],
            ['district_id' => 52, 'name' => 'Alfadanga'],
            ['district_id' => 52, 'name' => 'Boalmari'],
            ['district_id' => 52, 'name' => 'Sadarpur'],
            ['district_id' => 52, 'name' => 'Nagarkanda'],
            ['district_id' => 52, 'name' => 'Bhanga'],
            ['district_id' => 52, 'name' => 'Charbhadrasan'],
            ['district_id' => 52, 'name' => 'Madhukhali'],
            ['district_id' => 52, 'name' => 'Saltha'],
            ['district_id' => 53, 'name' => 'Panchagarh Sadar'],
            ['district_id' => 53, 'name' => 'Debiganj'],
            ['district_id' => 53, 'name' => 'Boda'],
            ['district_id' => 53, 'name' => 'Atwari'],
            ['district_id' => 53, 'name' => 'Tetulia'],
            ['district_id' => 54, 'name' => 'Nawabganj'],
            ['district_id' => 54, 'name' => 'Birganj'],
            ['district_id' => 54, 'name' => 'Ghoraghat'],
            ['district_id' => 54, 'name' => 'Birampur'],
            ['district_id' => 54, 'name' => 'Parbatipur'],
            ['district_id' => 54, 'name' => 'Bochaganj'],
            ['district_id' => 54, 'name' => 'Kaharol'],
            ['district_id' => 54, 'name' => 'Fulbari'],
            ['district_id' => 54, 'name' => 'Dinajpur Sadar'],
            ['district_id' => 54, 'name' => 'Hakimpur'],
            ['district_id' => 54, 'name' => 'Khansama'],
            ['district_id' => 54, 'name' => 'Biral'],
            ['district_id' => 54, 'name' => 'Chirirbandar'],
            ['district_id' => 55, 'name' => 'Lalmonirhat Sadar'],
            ['district_id' => 55, 'name' => 'Kaliganj'],
            ['district_id' => 55, 'name' => 'Hatibandha'],
            ['district_id' => 55, 'name' => 'Patgram'],
            ['district_id' => 55, 'name' => 'Aditmari'],
            ['district_id' => 56, 'name' => 'Saidpur'],
            ['district_id' => 56, 'name' => 'Domar'],
            ['district_id' => 56, 'name' => 'Dimla'],
            ['district_id' => 56, 'name' => 'Jaldhaka'],
            ['district_id' => 56, 'name' => 'Kishoreganj'],
            ['district_id' => 56, 'name' => 'Nilphamari Sadar'],
            ['district_id' => 57, 'name' => 'Sadullapur'],
            ['district_id' => 57, 'name' => 'Gaibandha Sadar'],
            ['district_id' => 57, 'name' => 'Palashbari'],
            ['district_id' => 57, 'name' => 'Saghata'],
            ['district_id' => 57, 'name' => 'Gobindaganj'],
            ['district_id' => 57, 'name' => 'Sundarganj'],
            ['district_id' => 57, 'name' => 'Phulchari'],
            ['district_id' => 58, 'name' => 'Thakurgaon Sadar'],
            ['district_id' => 58, 'name' => 'Pirganj'],
            ['district_id' => 58, 'name' => 'Ranisankail'],
            ['district_id' => 58, 'name' => 'Haripur'],
            ['district_id' => 58, 'name' => 'Baliadangi'],
            ['district_id' => 59, 'name' => 'Rangpur Sadar'],
            ['district_id' => 59, 'name' => 'Gangachara'],
            ['district_id' => 59, 'name' => 'Taraganj'],
            ['district_id' => 59, 'name' => 'Badarganj'],
            ['district_id' => 59, 'name' => 'Mithapukur'],
            ['district_id' => 59, 'name' => 'Pirganj'],
            ['district_id' => 59, 'name' => 'Kaunia'],
            ['district_id' => 59, 'name' => 'Pirgacha'],
            ['district_id' => 60, 'name' => 'Kurigram Sadar'],
            ['district_id' => 60, 'name' => 'Nageshwari'],
            ['district_id' => 60, 'name' => 'Bhurungamari'],
            ['district_id' => 60, 'name' => 'Phulbari'],
            ['district_id' => 60, 'name' => 'Rajarhat'],
            ['district_id' => 60, 'name' => 'Ulipur'],
            ['district_id' => 60, 'name' => 'Chilmari'],
            ['district_id' => 60, 'name' => 'Rowmari'],
            ['district_id' => 60, 'name' => 'Char Rajibpur'],
            ['district_id' => 61, 'name' => 'Sherpur Sadar'],
            ['district_id' => 61, 'name' => 'Nalitabari'],
            ['district_id' => 61, 'name' => 'Sreebardi'],
            ['district_id' => 61, 'name' => 'Nakla'],
            ['district_id' => 61, 'name' => 'Jhenaigati'],
            ['district_id' => 62, 'name' => 'Fulbaria'],
            ['district_id' => 62, 'name' => 'Trishal'],
            ['district_id' => 62, 'name' => 'Bhaluka'],
            ['district_id' => 62, 'name' => 'Muktagacha'],
            ['district_id' => 62, 'name' => 'Mymensingh Sadar'],
            ['district_id' => 62, 'name' => 'Dhobaura'],
            ['district_id' => 62, 'name' => 'Phulpur'],
            ['district_id' => 62, 'name' => 'Haluaghat'],
            ['district_id' => 62, 'name' => 'Gouripur'],
            ['district_id' => 62, 'name' => 'Gafargaon'],
            ['district_id' => 62, 'name' => 'Ishwarganj'],
            ['district_id' => 62, 'name' => 'Nandail'],
            ['district_id' => 62, 'name' => 'Tarakanda'],
            ['district_id' => 63, 'name' => 'Jamalpur Sadar'],
            ['district_id' => 63, 'name' => 'Melandaha'],
            ['district_id' => 63, 'name' => 'Islampur'],
            ['district_id' => 63, 'name' => 'Dewanganj'],
            ['district_id' => 63, 'name' => 'Sarishabari'],
            ['district_id' => 63, 'name' => 'Madarganj'],
            ['district_id' => 63, 'name' => 'Bakshiganj'],
            ['district_id' => 64, 'name' => 'Barhatta'],
            ['district_id' => 64, 'name' => 'Durgapur'],
            ['district_id' => 64, 'name' => 'Kendua'],
            ['district_id' => 64, 'name' => 'Atpara'],
            ['district_id' => 64, 'name' => 'Madan'],
            ['district_id' => 64, 'name' => 'Khaliajuri'],
            ['district_id' => 64, 'name' => 'Kalmakanda'],
            ['district_id' => 64, 'name' => 'Mohanganj'],
            ['district_id' => 64, 'name' => 'Purbadhala'],
            ['district_id' => 64, 'name' => 'Netrokona Sadar'],
            ['district_id' => 39, 'name' => 'Madhyanagar'],
            ['district_id' => 38, 'name' => 'Shayestaganj'],
            ['district_id' => 32, 'name' => 'Indurkani'],
            ['district_id' => 50, 'name' => 'Dasar'],
            ['district_id' => 15, 'name' => 'Motihar'],
            ['district_id' => 15, 'name' => 'Shah Makhdum'],
            ['district_id' => 15, 'name' => 'Boalia'],
            ['district_id' => 15, 'name' => 'Rajpara'],
            ['district_id' => 36, 'name' => 'Shah Paran'],
            ['district_id' => 36, 'name' => 'South Surma'],
            ['district_id' => 36, 'name' => 'Moglabazar'],
            ['district_id' => 36, 'name' => 'Jalalabad'],
            ['district_id' => 36, 'name' => 'Bimanbandar'],
            ['district_id' => 27, 'name' => 'Kotwali'],
            ['district_id' => 27, 'name' => 'Khalishpur'],
            ['district_id' => 27, 'name' => 'Sonadanga'],
            ['district_id' => 27, 'name' => 'Daulatpur'],
            ['district_id' => 27, 'name' => 'Khan Jahan Ali'],
            ['district_id' => 59, 'name' => 'Kawnia'],
            ['district_id' => 8, 'name' => 'Bimanbandar'],
            ['district_id' => 8, 'name' => 'Kazirhat'],
            ['district_id' => 8, 'name' => 'Kotwali'],
            ['district_id' => 8, 'name' => 'Sadarghat'],
            ['district_id' => 8, 'name' => 'Patenga'],
            ['district_id' => 8, 'name' => 'Panchlaish'],
            ['district_id' => 8, 'name' => 'Pahartali'],
            ['district_id' => 8, 'name' => 'Khulshi'],
            ['district_id' => 8, 'name' => 'Halishahar'],
            ['district_id' => 8, 'name' => 'Double Mooring'],
            ['district_id' => 8, 'name' => 'Chittagong Kotwali'],
            ['district_id' => 8, 'name' => 'Chawkbazar'],
            ['district_id' => 8, 'name' => 'Chandgaon'],
            ['district_id' => 8, 'name' => 'Bhujpur'],
            ['district_id' => 8, 'name' => 'Bandar'],
            ['district_id' => 8, 'name' => 'Bakolia'],
            ['district_id' => 8, 'name' => 'Bayezid'],
            ['district_id' => 8, 'name' => 'Akbar Shah'],
            ['district_id' => 47, 'name' => 'Wari'],
            ['district_id' => 47, 'name' => 'Vatara'],
            ['district_id' => 47, 'name' => 'Bhashantek'],
            ['district_id' => 47, 'name' => 'Uttar Khan'],
            ['district_id' => 47, 'name' => 'Uttara West'],
            ['district_id' => 47, 'name' => 'Uttara East'],
            ['district_id' => 47, 'name' => 'Turag'],
            ['district_id' => 47, 'name' => 'Tejgaon'],
            ['district_id' => 47, 'name' => 'Tejgaon Industrial'],
            ['district_id' => 47, 'name' => 'Sher-e-Bangla Nagar'],
            ['district_id' => 47, 'name' => 'Shyampur'],
            ['district_id' => 47, 'name' => 'Sutrapur'],
            ['district_id' => 47, 'name' => 'Shahjahanpur'],
            ['district_id' => 47, 'name' => 'Shahbagh'],
            ['district_id' => 47, 'name' => 'Shah Ali'],
            ['district_id' => 47, 'name' => 'Sabujbagh'],
            ['district_id' => 47, 'name' => 'Rupnagar'],
            ['district_id' => 47, 'name' => 'Rampura'],
            ['district_id' => 47, 'name' => 'Ramna'],
            ['district_id' => 47, 'name' => 'Paltan'],
            ['district_id' => 47, 'name' => 'Pallabi'],
            ['district_id' => 47, 'name' => 'New Market'],
            ['district_id' => 47, 'name' => 'Mugda'],
            ['district_id' => 47, 'name' => 'Motijheel'],
            ['district_id' => 47, 'name' => 'Mohammadpur'],
            ['district_id' => 47, 'name' => 'Mirpur Model'],
            ['district_id' => 47, 'name' => 'Lalbagh'],
            ['district_id' => 47, 'name' => 'Kotwali'],
            ['district_id' => 47, 'name' => 'Kadamtali'],
            ['district_id' => 47, 'name' => 'Khilkhet'],
            ['district_id' => 47, 'name' => 'Khilgaon'],
            ['district_id' => 47, 'name' => 'Kamrangirchar'],
            ['district_id' => 47, 'name' => 'Kalabagan'],
            ['district_id' => 47, 'name' => 'Kafrul'],
            ['district_id' => 47, 'name' => 'Jatrabari'],
            ['district_id' => 47, 'name' => 'Hazaribagh'],
            ['district_id' => 47, 'name' => 'Gulshan'],
            ['district_id' => 47, 'name' => 'Gandaria'],
            ['district_id' => 47, 'name' => 'Dhanmondi'],
            ['district_id' => 47, 'name' => 'Demra'],
            ['district_id' => 47, 'name' => 'Darus Salam'],
            ['district_id' => 47, 'name' => 'Dakshin Khan'],
            ['district_id' => 47, 'name' => 'Chawkbazar'],
            ['district_id' => 47, 'name' => 'Cantonment'],
            ['district_id' => 47, 'name' => 'Bimanbandar'],
            ['district_id' => 47, 'name' => 'Bangshal'],
            ['district_id' => 47, 'name' => 'Banani'],
            ['district_id' => 47, 'name' => 'Badda'],
            ['district_id' => 47, 'name' => 'Adabor'],
        ];

        DB::table('upazilas')->insert($upazilas);

    }
}
