<?php

namespace App\Lib;

class Geo
{
    public static function divisions()
    {
        return [
            1 => ['name' => 'Chattogram'],
            2 => ['name' => 'Rajshahi'],
            3 => ['name' => 'Khulna'],
            4 => ['name' => 'Barisal'],
            5 => ['name' => 'Sylhet'],
            6 => ['name' => 'Dhaka'],
            7 => ['name' => 'Rangpur'],
            8 => ['name' => 'Mymensingh'],
        ];
    }

    public static function districts($division = null)
    {
        if ($division) {
            return array_filter(self::districts(), function ($district) use ($division) {
                return $district['division_id'] == $division;
            });
        }

        return [
            1 => ['division_id' => 1, 'name' => 'Cumilla'],
            2 => ['division_id' => 1, 'name' => 'Feni'],
            3 => ['division_id' => 1, 'name' => 'Brahmanbaria'],
            4 => ['division_id' => 1, 'name' => 'Rangamati'],
            5 => ['division_id' => 1, 'name' => 'Noakhali'],
            6 => ['division_id' => 1, 'name' => 'Chandpur'],
            7 => ['division_id' => 1, 'name' => 'Lakshmipur'],
            8 => ['division_id' => 1, 'name' => 'Chattogram'],
            9 => ['division_id' => 1, 'name' => "Cox's Bazar"],
            10 => ['division_id' => 1, 'name' => 'Khagrachari'],
            11 => ['division_id' => 1, 'name' => 'Bandarban'],
            12 => ['division_id' => 2, 'name' => 'Sirajganj'],
            13 => ['division_id' => 2, 'name' => 'Pabna'],
            14 => ['division_id' => 2, 'name' => 'Bogura'],
            15 => ['division_id' => 2, 'name' => 'Rajshahi'],
            16 => ['division_id' => 2, 'name' => 'Natore'],
            17 => ['division_id' => 2, 'name' => 'Joypurhat'],
            18 => ['division_id' => 2, 'name' => 'Chapainawabganj'],
            19 => ['division_id' => 2, 'name' => 'Naogaon'],
            20 => ['division_id' => 3, 'name' => 'Jashore'],
            21 => ['division_id' => 3, 'name' => 'Satkhira'],
            22 => ['division_id' => 3, 'name' => 'Meherpur'],
            23 => ['division_id' => 3, 'name' => 'Narail'],
            24 => ['division_id' => 3, 'name' => 'Chuadanga'],
            25 => ['division_id' => 3, 'name' => 'Kushtia'],
            26 => ['division_id' => 3, 'name' => 'Magura'],
            27 => ['division_id' => 3, 'name' => 'Khulna'],
            28 => ['division_id' => 3, 'name' => 'Bagerhat'],
            29 => ['division_id' => 3, 'name' => 'Jhenaidah'],
            30 => ['division_id' => 4, 'name' => 'Jhalokati'],
            31 => ['division_id' => 4, 'name' => 'Patuakhali'],
            32 => ['division_id' => 4, 'name' => 'Pirojpur'],
            33 => ['division_id' => 4, 'name' => 'Barisal'],
            34 => ['division_id' => 4, 'name' => 'Bhola'],
            35 => ['division_id' => 4, 'name' => 'Barguna'],
            36 => ['division_id' => 5, 'name' => 'Sylhet'],
            37 => ['division_id' => 5, 'name' => 'Moulvibazar'],
            38 => ['division_id' => 5, 'name' => 'Habiganj'],
            39 => ['division_id' => 5, 'name' => 'Sunamganj'],
            40 => ['division_id' => 6, 'name' => 'Narsingdi'],
            41 => ['division_id' => 6, 'name' => 'Gazipur'],
            42 => ['division_id' => 6, 'name' => 'Shariatpur'],
            43 => ['division_id' => 6, 'name' => 'Narayanganj'],
            44 => ['division_id' => 6, 'name' => 'Tangail'],
            45 => ['division_id' => 6, 'name' => 'Kishoreganj'],
            46 => ['division_id' => 6, 'name' => 'Manikganj'],
            47 => ['division_id' => 6, 'name' => 'Dhaka'],
            48 => ['division_id' => 6, 'name' => 'Munshiganj'],
            49 => ['division_id' => 6, 'name' => 'Rajbari'],
            50 => ['division_id' => 6, 'name' => 'Madaripur'],
            51 => ['division_id' => 6, 'name' => 'Gopalganj'],
            52 => ['division_id' => 6, 'name' => 'Faridpur'],
            53 => ['division_id' => 7, 'name' => 'Panchagarh'],
            54 => ['division_id' => 7, 'name' => 'Dinajpur'],
            55 => ['division_id' => 7, 'name' => 'Lalmonirhat'],
            56 => ['division_id' => 7, 'name' => 'Nilphamari'],
            57 => ['division_id' => 7, 'name' => 'Gaibandha'],
            58 => ['division_id' => 7, 'name' => 'Thakurgaon'],
            59 => ['division_id' => 7, 'name' => 'Rangpur'],
            60 => ['division_id' => 7, 'name' => 'Kurigram'],
            61 => ['division_id' => 8, 'name' => 'Sherpur'],
            62 => ['division_id' => 8, 'name' => 'Mymensingh'],
            63 => ['division_id' => 8, 'name' => 'Jamalpur'],
            64 => ['division_id' => 8, 'name' => 'Netrokona'],
        ];
    }

    public static function getDistrictIdByName($name)
    {
        $districts = static::districts();
        foreach ($districts as $id => $district) {
            if ($district['name'] === $name) {
                return $id; // Return the district ID if the name matches
            }
        }

        return null; // Return null if no match is found
    }

    public static function upazillas($district = null)
    {
        if ($district) {
            return array_filter(self::upazillas(), function ($upazilla) use ($district) {
                return $upazilla['district_id'] == $district;
            });
        }

        return [
            1 => ['district_id' => 1, 'name' => 'Debidwar'],
            2 => ['district_id' => 1, 'name' => 'Barura'],
            3 => ['district_id' => 1, 'name' => 'Brahmanpara'],
            4 => ['district_id' => 1, 'name' => 'Chandina'],
            5 => ['district_id' => 1, 'name' => 'Chauddagram'],
            6 => ['district_id' => 1, 'name' => 'Daudkandi'],
            7 => ['district_id' => 1, 'name' => 'Homna'],
            8 => ['district_id' => 1, 'name' => 'Laksam'],
            9 => ['district_id' => 1, 'name' => 'Muradnagar'],
            10 => ['district_id' => 1, 'name' => 'Nangalkot'],
            11 => ['district_id' => 1, 'name' => 'Cumilla Sadar'],
            12 => ['district_id' => 1, 'name' => 'Meghna'],
            13 => ['district_id' => 1, 'name' => 'Monohargonj'],
            14 => ['district_id' => 1, 'name' => 'Cumilla Sadar Dakshin'],
            15 => ['district_id' => 1, 'name' => 'Titas'],
            16 => ['district_id' => 1, 'name' => 'Burichang'],
            17 => ['district_id' => 1, 'name' => 'Lalmai'],
            18 => ['district_id' => 2, 'name' => 'Chhagalnaiya'],
            19 => ['district_id' => 2, 'name' => 'Feni Sadar'],
            20 => ['district_id' => 2, 'name' => 'Sonagazi'],
            21 => ['district_id' => 2, 'name' => 'Fulgazi'],
            22 => ['district_id' => 2, 'name' => 'Parshuram'],
            23 => ['district_id' => 2, 'name' => 'Daganbhuiyan'],
            24 => ['district_id' => 3, 'name' => 'Brahmanbaria Sadar'],
            25 => ['district_id' => 3, 'name' => 'Kasba'],
            26 => ['district_id' => 3, 'name' => 'Nasirnagar'],
            27 => ['district_id' => 3, 'name' => 'Sarail'],
            28 => ['district_id' => 3, 'name' => 'Ashuganj'],
            29 => ['district_id' => 3, 'name' => 'Akhaura'],
            30 => ['district_id' => 3, 'name' => 'Nabinagar'],
            31 => ['district_id' => 3, 'name' => 'Bancharampur'],
            32 => ['district_id' => 3, 'name' => 'Bijoynagar'],
            33 => ['district_id' => 4, 'name' => 'Rangamati Sadar'],
            34 => ['district_id' => 4, 'name' => 'Kaptai'],
            35 => ['district_id' => 4, 'name' => 'Kawkhali'],
            36 => ['district_id' => 4, 'name' => 'Baghaichari'],
            37 => ['district_id' => 4, 'name' => 'Barkal'],
            38 => ['district_id' => 4, 'name' => 'Langadu'],
            39 => ['district_id' => 4, 'name' => 'Rajasthali'],
            40 => ['district_id' => 4, 'name' => 'Belaichari'],
            41 => ['district_id' => 4, 'name' => 'Juraichari'],
            42 => ['district_id' => 4, 'name' => 'Naniarchar'],
            43 => ['district_id' => 5, 'name' => 'Noakhali Sadar'],
            44 => ['district_id' => 5, 'name' => 'Companiganj'],
            45 => ['district_id' => 5, 'name' => 'Begumganj'],
            46 => ['district_id' => 5, 'name' => 'Hatia'],
            47 => ['district_id' => 5, 'name' => 'Subarnachar'],
            48 => ['district_id' => 5, 'name' => 'Kabirhat'],
            49 => ['district_id' => 5, 'name' => 'Senbagh'],
            50 => ['district_id' => 5, 'name' => 'Chatkhil'],
            51 => ['district_id' => 5, 'name' => 'Sonaimuri'],
            52 => ['district_id' => 6, 'name' => 'Haimchar'],
            53 => ['district_id' => 6, 'name' => 'Kachua'],
            54 => ['district_id' => 6, 'name' => 'Shahrasti'],
            55 => ['district_id' => 6, 'name' => 'Chandpur Sadar'],
            56 => ['district_id' => 6, 'name' => 'Matlab South'],
            57 => ['district_id' => 6, 'name' => 'Haziganj'],
            58 => ['district_id' => 6, 'name' => 'Matlab North'],
            59 => ['district_id' => 6, 'name' => 'Faridganj'],
            60 => ['district_id' => 7, 'name' => 'Lakshmipur Sadar'],
            61 => ['district_id' => 7, 'name' => 'Kamalnagar'],
            62 => ['district_id' => 7, 'name' => 'Raipur'],
            63 => ['district_id' => 7, 'name' => 'Ramgati'],
            64 => ['district_id' => 7, 'name' => 'Ramganj'],
            65 => ['district_id' => 8, 'name' => 'Rangunia'],
            66 => ['district_id' => 8, 'name' => 'Sitakunda'],
            67 => ['district_id' => 8, 'name' => 'Mirsharai'],
            68 => ['district_id' => 8, 'name' => 'Patiya'],
            69 => ['district_id' => 8, 'name' => 'Sandwip'],
            70 => ['district_id' => 8, 'name' => 'Banshkhali'],
            71 => ['district_id' => 8, 'name' => 'Boalkhali'],
            72 => ['district_id' => 8, 'name' => 'Anwara'],
            73 => ['district_id' => 8, 'name' => 'Chandanaish'],
            74 => ['district_id' => 8, 'name' => 'Satkania'],
            75 => ['district_id' => 8, 'name' => 'Lohagara'],
            76 => ['district_id' => 8, 'name' => 'Hathazari'],
            77 => ['district_id' => 8, 'name' => 'Fatikchhari'],
            78 => ['district_id' => 8, 'name' => 'Raozan'],
            79 => ['district_id' => 8, 'name' => 'Karnafuli'],
            80 => ['district_id' => 9, 'name' => "Cox's Bazar Sadar"],
            81 => ['district_id' => 9, 'name' => 'Chakaria'],
            82 => ['district_id' => 9, 'name' => 'Kutubdia'],
            83 => ['district_id' => 9, 'name' => 'Ukhiya'],
            84 => ['district_id' => 9, 'name' => 'Moheshkhali'],
            85 => ['district_id' => 9, 'name' => 'Pekua'],
            86 => ['district_id' => 9, 'name' => 'Ramu'],
            87 => ['district_id' => 9, 'name' => 'Teknaf'],
            88 => ['district_id' => 10, 'name' => 'Khagrachari Sadar'],
            89 => ['district_id' => 10, 'name' => 'Dighinala'],
            90 => ['district_id' => 10, 'name' => 'Panchhari'],
            91 => ['district_id' => 10, 'name' => 'Luxmichari'],
            92 => ['district_id' => 10, 'name' => 'Mahalchari'],
            93 => ['district_id' => 10, 'name' => 'Manikchari'],
            94 => ['district_id' => 10, 'name' => 'Ramgarh'],
            95 => ['district_id' => 10, 'name' => 'Matiranga'],
            96 => ['district_id' => 10, 'name' => 'Guimara'],
            97 => ['district_id' => 11, 'name' => 'Bandarban Sadar'],
            98 => ['district_id' => 11, 'name' => 'Alikadam'],
            99 => ['district_id' => 11, 'name' => 'Naikhongchhari'],
            100 => ['district_id' => 11, 'name' => 'Rowangchhari'],
            101 => ['district_id' => 11, 'name' => 'Lama'],
            102 => ['district_id' => 11, 'name' => 'Ruma'],
            103 => ['district_id' => 11, 'name' => 'Thanchi'],
            104 => ['district_id' => 12, 'name' => 'Belkuchi'],
            105 => ['district_id' => 12, 'name' => 'Chauhali'],
            106 => ['district_id' => 12, 'name' => 'Kamarkhanda'],
            107 => ['district_id' => 12, 'name' => 'Kazipur'],
            108 => ['district_id' => 12, 'name' => 'Raiganj'],
            109 => ['district_id' => 12, 'name' => 'Shahjadpur'],
            110 => ['district_id' => 12, 'name' => 'Sirajganj Sadar'],
            111 => ['district_id' => 12, 'name' => 'Tarash'],
            112 => ['district_id' => 12, 'name' => 'Ullapara'],
            113 => ['district_id' => 13, 'name' => 'Sujanagar'],
            114 => ['district_id' => 13, 'name' => 'Ishwardi'],
            115 => ['district_id' => 13, 'name' => 'Bhangura'],
            116 => ['district_id' => 13, 'name' => 'Pabna Sadar'],
            117 => ['district_id' => 13, 'name' => 'Bera'],
            118 => ['district_id' => 13, 'name' => 'Atghoria'],
            119 => ['district_id' => 13, 'name' => 'Chatmohar'],
            120 => ['district_id' => 13, 'name' => 'Santhia'],
            121 => ['district_id' => 13, 'name' => 'Faridpur'],
            122 => ['district_id' => 14, 'name' => 'Kahaloo'],
            123 => ['district_id' => 14, 'name' => 'Bogra Sadar'],
            124 => ['district_id' => 14, 'name' => 'Sariakandi'],
            125 => ['district_id' => 14, 'name' => 'Shajahanpur'],
            126 => ['district_id' => 14, 'name' => 'Dupchanchia'],
            127 => ['district_id' => 14, 'name' => 'Adamdighi'],
            128 => ['district_id' => 14, 'name' => 'Nandigram'],
            129 => ['district_id' => 14, 'name' => 'Sonatala'],
            130 => ['district_id' => 14, 'name' => 'Dhunat'],
            131 => ['district_id' => 14, 'name' => 'Gabtali'],
            132 => ['district_id' => 14, 'name' => 'Sherpur'],
            133 => ['district_id' => 14, 'name' => 'Shibganj'],
            134 => ['district_id' => 15, 'name' => 'Paba'],
            135 => ['district_id' => 15, 'name' => 'Durgapur'],
            136 => ['district_id' => 15, 'name' => 'Mohanpur'],
            137 => ['district_id' => 15, 'name' => 'Charghat'],
            138 => ['district_id' => 15, 'name' => 'Puthia'],
            139 => ['district_id' => 15, 'name' => 'Bagha'],
            140 => ['district_id' => 15, 'name' => 'Godagari'],
            141 => ['district_id' => 15, 'name' => 'Tanore'],
            142 => ['district_id' => 15, 'name' => 'Bagmara'],
            143 => ['district_id' => 16, 'name' => 'Natore Sadar'],
            144 => ['district_id' => 16, 'name' => 'Singra'],
            145 => ['district_id' => 16, 'name' => 'Baraigram'],
            146 => ['district_id' => 16, 'name' => 'Bagatipara'],
            147 => ['district_id' => 16, 'name' => 'Lalpur'],
            148 => ['district_id' => 16, 'name' => 'Gurudaspur'],
            149 => ['district_id' => 16, 'name' => 'Naldanga'],
            150 => ['district_id' => 17, 'name' => 'Akkelpur'],
            151 => ['district_id' => 17, 'name' => 'Kalai'],
            152 => ['district_id' => 17, 'name' => 'Khetlal'],
            153 => ['district_id' => 17, 'name' => 'Panchbibi'],
            154 => ['district_id' => 17, 'name' => 'Joypurhat Sadar'],
            155 => ['district_id' => 18, 'name' => 'Nawabganj Sadar'],
            156 => ['district_id' => 18, 'name' => 'Gomastapur'],
            157 => ['district_id' => 18, 'name' => 'Nachole'],
            158 => ['district_id' => 18, 'name' => 'Bholahat'],
            159 => ['district_id' => 18, 'name' => 'Shibganj'],
            160 => ['district_id' => 19, 'name' => 'Mohadevpur'],
            161 => ['district_id' => 19, 'name' => 'Badalgachi'],
            162 => ['district_id' => 19, 'name' => 'Patnitala'],
            163 => ['district_id' => 19, 'name' => 'Dhamoirhat'],
            164 => ['district_id' => 19, 'name' => 'Niamatpur'],
            165 => ['district_id' => 19, 'name' => 'Manda'],
            166 => ['district_id' => 19, 'name' => 'Atrai'],
            167 => ['district_id' => 19, 'name' => 'Raninagar'],
            168 => ['district_id' => 19, 'name' => 'Naogaon Sadar'],
            169 => ['district_id' => 19, 'name' => 'Porsha'],
            170 => ['district_id' => 19, 'name' => 'Sapahar'],
            171 => ['district_id' => 20, 'name' => 'Manirampur'],
            172 => ['district_id' => 20, 'name' => 'Abhaynagar'],
            173 => ['district_id' => 20, 'name' => 'Bagherpara'],
            174 => ['district_id' => 20, 'name' => 'Chowgacha'],
            175 => ['district_id' => 20, 'name' => 'Jhikargacha'],
            176 => ['district_id' => 20, 'name' => 'Keshabpur'],
            177 => ['district_id' => 20, 'name' => 'Jashore Sadar'],
            178 => ['district_id' => 20, 'name' => 'Sharsha'],
            179 => ['district_id' => 21, 'name' => 'Assasuni'],
            180 => ['district_id' => 21, 'name' => 'Debhata'],
            181 => ['district_id' => 21, 'name' => 'Kalaroa'],
            182 => ['district_id' => 21, 'name' => 'Satkhira Sadar'],
            183 => ['district_id' => 21, 'name' => 'Shyamnagar'],
            184 => ['district_id' => 21, 'name' => 'Tala'],
            185 => ['district_id' => 21, 'name' => 'Kaliganj'],
            186 => ['district_id' => 22, 'name' => 'Mujibnagar'],
            187 => ['district_id' => 22, 'name' => 'Meherpur Sadar'],
            188 => ['district_id' => 22, 'name' => 'Gangni'],
            189 => ['district_id' => 23, 'name' => 'Narail Sadar'],
            190 => ['district_id' => 23, 'name' => 'Lohagara'],
            191 => ['district_id' => 23, 'name' => 'Kalia'],
            192 => ['district_id' => 24, 'name' => 'Chuadanga Sadar'],
            193 => ['district_id' => 24, 'name' => 'Alamdanga'],
            194 => ['district_id' => 24, 'name' => 'Damurhuda'],
            195 => ['district_id' => 24, 'name' => 'Jibannagar'],
            196 => ['district_id' => 25, 'name' => 'Kushtia Sadar'],
            197 => ['district_id' => 25, 'name' => 'Kumarkhali'],
            198 => ['district_id' => 25, 'name' => 'Khoksa'],
            199 => ['district_id' => 25, 'name' => 'Mirpur'],
            200 => ['district_id' => 25, 'name' => 'Daulatpur'],
            201 => ['district_id' => 25, 'name' => 'Bheramara'],
            202 => ['district_id' => 26, 'name' => 'Shalikha'],
            203 => ['district_id' => 26, 'name' => 'Sreepur'],
            204 => ['district_id' => 26, 'name' => 'Magura Sadar'],
            205 => ['district_id' => 26, 'name' => 'Mohammadpur'],
            206 => ['district_id' => 27, 'name' => 'Paikgacha'],
            207 => ['district_id' => 27, 'name' => 'Phultala'],
            208 => ['district_id' => 27, 'name' => 'Dighalia'],
            209 => ['district_id' => 27, 'name' => 'Rupsha'],
            210 => ['district_id' => 27, 'name' => 'Terokhada'],
            211 => ['district_id' => 27, 'name' => 'Dumuria'],
            212 => ['district_id' => 27, 'name' => 'Batiaghata'],
            213 => ['district_id' => 27, 'name' => 'Dakop'],
            214 => ['district_id' => 27, 'name' => 'Koyra'],
            215 => ['district_id' => 28, 'name' => 'Fakirhat'],
            216 => ['district_id' => 28, 'name' => 'Bagerhat Sadar'],
            217 => ['district_id' => 28, 'name' => 'Mollahat'],
            218 => ['district_id' => 28, 'name' => 'Sarankhola'],
            219 => ['district_id' => 28, 'name' => 'Rampal'],
            220 => ['district_id' => 28, 'name' => 'Morrelganj'],
            221 => ['district_id' => 28, 'name' => 'Kachua'],
            222 => ['district_id' => 28, 'name' => 'Mongla'],
            223 => ['district_id' => 28, 'name' => 'Chitalmari'],
            224 => ['district_id' => 29, 'name' => 'Jhenaidah Sadar'],
            225 => ['district_id' => 29, 'name' => 'Shailkupa'],
            226 => ['district_id' => 29, 'name' => 'Harinakundu'],
            227 => ['district_id' => 29, 'name' => 'Kaliganj'],
            228 => ['district_id' => 29, 'name' => 'Kotchandpur'],
            229 => ['district_id' => 29, 'name' => 'Maheshpur'],
            230 => ['district_id' => 30, 'name' => 'Jhalakathi Sadar'],
            231 => ['district_id' => 30, 'name' => 'Kathalia'],
            232 => ['district_id' => 30, 'name' => 'Nalchity'],
            233 => ['district_id' => 30, 'name' => 'Rajapur'],
            234 => ['district_id' => 31, 'name' => 'Bauphal'],
            235 => ['district_id' => 31, 'name' => 'Patuakhali Sadar'],
            236 => ['district_id' => 31, 'name' => 'Dumki'],
            237 => ['district_id' => 31, 'name' => 'Dashmina'],
            238 => ['district_id' => 31, 'name' => 'Kalapara'],
            239 => ['district_id' => 31, 'name' => 'Mirzaganj'],
            240 => ['district_id' => 31, 'name' => 'Galachipa'],
            241 => ['district_id' => 31, 'name' => 'Rangabali'],
            242 => ['district_id' => 32, 'name' => 'Pirojpur Sadar'],
            243 => ['district_id' => 32, 'name' => 'Nazirpur'],
            244 => ['district_id' => 32, 'name' => 'Kawkhali'],
            245 => ['district_id' => 32, 'name' => 'Zianagar'],
            246 => ['district_id' => 32, 'name' => 'Bhandaria'],
            247 => ['district_id' => 32, 'name' => 'Mathbaria'],
            248 => ['district_id' => 32, 'name' => 'Nesarabad(Swarupkati)'],
            249 => ['district_id' => 33, 'name' => 'Barisal Sadar'],
            250 => ['district_id' => 33, 'name' => 'Bakerganj'],
            251 => ['district_id' => 33, 'name' => 'Babuganj'],
            252 => ['district_id' => 33, 'name' => 'Wazirpur'],
            253 => ['district_id' => 33, 'name' => 'Banaripara'],
            254 => ['district_id' => 33, 'name' => 'Gournadi'],
            255 => ['district_id' => 33, 'name' => 'Agailjhara'],
            256 => ['district_id' => 33, 'name' => 'Mehendiganj'],
            257 => ['district_id' => 33, 'name' => 'Muladi'],
            258 => ['district_id' => 33, 'name' => 'Hizla'],
            259 => ['district_id' => 34, 'name' => 'Bhola Sadar'],
            260 => ['district_id' => 34, 'name' => 'Borhanuddin'],
            261 => ['district_id' => 34, 'name' => 'Char Fasson'],
            262 => ['district_id' => 34, 'name' => 'Daulatkhan'],
            263 => ['district_id' => 34, 'name' => 'Manpura'],
            264 => ['district_id' => 34, 'name' => 'Tazumuddin'],
            265 => ['district_id' => 34, 'name' => 'Lalmohan'],
            266 => ['district_id' => 35, 'name' => 'Amtali'],
            267 => ['district_id' => 35, 'name' => 'Barguna Sadar'],
            268 => ['district_id' => 35, 'name' => 'Betagi'],
            269 => ['district_id' => 35, 'name' => 'Bamna'],
            270 => ['district_id' => 35, 'name' => 'Patharghata'],
            271 => ['district_id' => 35, 'name' => 'Taltali'],
            272 => ['district_id' => 36, 'name' => 'Balaganj'],
            273 => ['district_id' => 36, 'name' => 'Beanibazar'],
            274 => ['district_id' => 36, 'name' => 'Bishwanath'],
            275 => ['district_id' => 36, 'name' => 'Companiganj'],
            276 => ['district_id' => 36, 'name' => 'Fenchuganj'],
            277 => ['district_id' => 36, 'name' => 'Golapganj'],
            278 => ['district_id' => 36, 'name' => 'Gowainghat'],
            279 => ['district_id' => 36, 'name' => 'Jaintiapur'],
            280 => ['district_id' => 36, 'name' => 'Kanaighat'],
            281 => ['district_id' => 36, 'name' => 'Sylhet Sadar'],
            282 => ['district_id' => 36, 'name' => 'Zakiganj'],
            283 => ['district_id' => 36, 'name' => 'Dakshin Surma'],
            284 => ['district_id' => 36, 'name' => 'Osmaninagar'],
            285 => ['district_id' => 37, 'name' => 'Barlekha'],
            286 => ['district_id' => 37, 'name' => 'Kamalganj'],
            287 => ['district_id' => 37, 'name' => 'Kulaura'],
            288 => ['district_id' => 37, 'name' => 'Moulvibazar Sadar'],
            289 => ['district_id' => 37, 'name' => 'Rajnagar'],
            290 => ['district_id' => 37, 'name' => 'Sreemangal'],
            291 => ['district_id' => 37, 'name' => 'Juri'],
            292 => ['district_id' => 38, 'name' => 'Nabiganj'],
            293 => ['district_id' => 38, 'name' => 'Bahubal'],
            294 => ['district_id' => 38, 'name' => 'Ajmiriganj'],
            295 => ['district_id' => 38, 'name' => 'Baniachong'],
            296 => ['district_id' => 38, 'name' => 'Lakhai'],
            297 => ['district_id' => 38, 'name' => 'Chunarughat'],
            298 => ['district_id' => 38, 'name' => 'Habiganj Sadar'],
            299 => ['district_id' => 38, 'name' => 'Madhabpur'],
            300 => ['district_id' => 39, 'name' => 'Sunamganj Sadar'],
            301 => ['district_id' => 39, 'name' => 'South Sunamganj'],
            302 => ['district_id' => 39, 'name' => 'Bishwamvarpur'],
            303 => ['district_id' => 39, 'name' => 'Chhatak'],
            304 => ['district_id' => 39, 'name' => 'Jagannathpur'],
            305 => ['district_id' => 39, 'name' => 'Dowarabazar'],
            306 => ['district_id' => 39, 'name' => 'Tahirpur'],
            307 => ['district_id' => 39, 'name' => 'Dharmapasha'],
            308 => ['district_id' => 39, 'name' => 'Jamalganj'],
            309 => ['district_id' => 39, 'name' => 'Sullah'],
            310 => ['district_id' => 39, 'name' => 'Derai'],
            311 => ['district_id' => 40, 'name' => 'Belabo'],
            312 => ['district_id' => 40, 'name' => 'Monohardi'],
            313 => ['district_id' => 40, 'name' => 'Narsingdi Sadar'],
            314 => ['district_id' => 40, 'name' => 'Palash'],
            315 => ['district_id' => 40, 'name' => 'Raipura'],
            316 => ['district_id' => 40, 'name' => 'Shibpur'],
            317 => ['district_id' => 41, 'name' => 'Kaliganj'],
            318 => ['district_id' => 41, 'name' => 'Kaliakair'],
            319 => ['district_id' => 41, 'name' => 'Kapasia'],
            320 => ['district_id' => 41, 'name' => 'Gazipur Sadar'],
            321 => ['district_id' => 41, 'name' => 'Sreepur'],
            322 => ['district_id' => 42, 'name' => 'Shariatpur Sadar'],
            323 => ['district_id' => 42, 'name' => 'Naria'],
            324 => ['district_id' => 42, 'name' => 'Zajira'],
            325 => ['district_id' => 42, 'name' => 'Gosairhat'],
            326 => ['district_id' => 42, 'name' => 'Bhedarganj'],
            327 => ['district_id' => 42, 'name' => 'Damudya'],
            328 => ['district_id' => 43, 'name' => 'Araihazar'],
            329 => ['district_id' => 43, 'name' => 'Bandar'],
            330 => ['district_id' => 43, 'name' => 'Narayanganj Sadar'],
            331 => ['district_id' => 43, 'name' => 'Rupganj'],
            332 => ['district_id' => 43, 'name' => 'Sonargaon'],
            333 => ['district_id' => 44, 'name' => 'Basail'],
            334 => ['district_id' => 44, 'name' => 'Bhuapur'],
            335 => ['district_id' => 44, 'name' => 'Delduar'],
            336 => ['district_id' => 44, 'name' => 'Ghatail'],
            337 => ['district_id' => 44, 'name' => 'Gopalpur'],
            338 => ['district_id' => 44, 'name' => 'Madhupur'],
            339 => ['district_id' => 44, 'name' => 'Mirzapur'],
            340 => ['district_id' => 44, 'name' => 'Nagarpur'],
            341 => ['district_id' => 44, 'name' => 'Sakhipur'],
            342 => ['district_id' => 44, 'name' => 'Tangail Sadar'],
            343 => ['district_id' => 44, 'name' => 'Kalihati'],
            344 => ['district_id' => 44, 'name' => 'Dhanbari'],
            345 => ['district_id' => 45, 'name' => 'Itna'],
            346 => ['district_id' => 45, 'name' => 'Katiadi'],
            347 => ['district_id' => 45, 'name' => 'Bhairab'],
            348 => ['district_id' => 45, 'name' => 'Tarail'],
            349 => ['district_id' => 45, 'name' => 'Hossainpur'],
            350 => ['district_id' => 45, 'name' => 'Pakundia'],
            351 => ['district_id' => 45, 'name' => 'Kuliarchar'],
            352 => ['district_id' => 45, 'name' => 'Kishoreganj Sadar'],
            353 => ['district_id' => 45, 'name' => 'Karimganj'],
            354 => ['district_id' => 45, 'name' => 'Bajitpur'],
            355 => ['district_id' => 45, 'name' => 'Austagram'],
            356 => ['district_id' => 45, 'name' => 'Mithamoin'],
            357 => ['district_id' => 45, 'name' => 'Nikli'],
            358 => ['district_id' => 46, 'name' => 'Harirampur'],
            359 => ['district_id' => 46, 'name' => 'Saturia'],
            360 => ['district_id' => 46, 'name' => 'Manikganj Sadar'],
            361 => ['district_id' => 46, 'name' => 'Ghior'],
            362 => ['district_id' => 46, 'name' => 'Shivalaya'],
            363 => ['district_id' => 46, 'name' => 'Doulatpur'],
            364 => ['district_id' => 46, 'name' => 'Singair'],
            365 => ['district_id' => 47, 'name' => 'Savar'],
            366 => ['district_id' => 47, 'name' => 'Dhamrai'],
            367 => ['district_id' => 47, 'name' => 'Keraniganj'],
            368 => ['district_id' => 47, 'name' => 'Nawabganj'],
            369 => ['district_id' => 47, 'name' => 'Dohar'],
            370 => ['district_id' => 48, 'name' => 'Munshiganj Sadar'],
            371 => ['district_id' => 48, 'name' => 'Sreenagar'],
            372 => ['district_id' => 48, 'name' => 'Sirajdikhan'],
            373 => ['district_id' => 48, 'name' => 'Louhajanj'],
            374 => ['district_id' => 48, 'name' => 'Gazaria'],
            375 => ['district_id' => 48, 'name' => 'Tongibari'],
            376 => ['district_id' => 49, 'name' => 'Rajbari Sadar'],
            377 => ['district_id' => 49, 'name' => 'Goalanda'],
            378 => ['district_id' => 49, 'name' => 'Pangsa'],
            379 => ['district_id' => 49, 'name' => 'Baliakandi'],
            380 => ['district_id' => 49, 'name' => 'Kalukhali'],
            381 => ['district_id' => 50, 'name' => 'Madaripur Sadar'],
            382 => ['district_id' => 50, 'name' => 'Shibchar'],
            383 => ['district_id' => 50, 'name' => 'Kalkini'],
            384 => ['district_id' => 50, 'name' => 'Rajoir'],
            385 => ['district_id' => 51, 'name' => 'Gopalganj Sadar'],
            386 => ['district_id' => 51, 'name' => 'Kashiani'],
            387 => ['district_id' => 51, 'name' => 'Tungipara'],
            388 => ['district_id' => 51, 'name' => 'Kotalipara'],
            389 => ['district_id' => 51, 'name' => 'Muksudpur'],
            390 => ['district_id' => 52, 'name' => 'Faridpur Sadar'],
            391 => ['district_id' => 52, 'name' => 'Alfadanga'],
            392 => ['district_id' => 52, 'name' => 'Boalmari'],
            393 => ['district_id' => 52, 'name' => 'Sadarpur'],
            394 => ['district_id' => 52, 'name' => 'Nagarkanda'],
            395 => ['district_id' => 52, 'name' => 'Bhanga'],
            396 => ['district_id' => 52, 'name' => 'Charbhadrasan'],
            397 => ['district_id' => 52, 'name' => 'Madhukhali'],
            398 => ['district_id' => 52, 'name' => 'Saltha'],
            399 => ['district_id' => 53, 'name' => 'Panchagarh Sadar'],
            400 => ['district_id' => 53, 'name' => 'Debiganj'],
            401 => ['district_id' => 53, 'name' => 'Boda'],
            402 => ['district_id' => 53, 'name' => 'Atwari'],
            403 => ['district_id' => 53, 'name' => 'Tetulia'],
            404 => ['district_id' => 54, 'name' => 'Nawabganj'],
            405 => ['district_id' => 54, 'name' => 'Birganj'],
            406 => ['district_id' => 54, 'name' => 'Ghoraghat'],
            407 => ['district_id' => 54, 'name' => 'Birampur'],
            408 => ['district_id' => 54, 'name' => 'Parbatipur'],
            409 => ['district_id' => 54, 'name' => 'Bochaganj'],
            410 => ['district_id' => 54, 'name' => 'Kaharol'],
            411 => ['district_id' => 54, 'name' => 'Fulbari'],
            412 => ['district_id' => 54, 'name' => 'Dinajpur Sadar'],
            413 => ['district_id' => 54, 'name' => 'Hakimpur'],
            414 => ['district_id' => 54, 'name' => 'Khansama'],
            415 => ['district_id' => 54, 'name' => 'Biral'],
            416 => ['district_id' => 54, 'name' => 'Chirirbandar'],
            417 => ['district_id' => 55, 'name' => 'Lalmonirhat Sadar'],
            418 => ['district_id' => 55, 'name' => 'Kaliganj'],
            419 => ['district_id' => 55, 'name' => 'Hatibandha'],
            420 => ['district_id' => 55, 'name' => 'Patgram'],
            421 => ['district_id' => 55, 'name' => 'Aditmari'],
            422 => ['district_id' => 56, 'name' => 'Saidpur'],
            423 => ['district_id' => 56, 'name' => 'Domar'],
            424 => ['district_id' => 56, 'name' => 'Dimla'],
            425 => ['district_id' => 56, 'name' => 'Jaldhaka'],
            426 => ['district_id' => 56, 'name' => 'Kishoreganj'],
            427 => ['district_id' => 56, 'name' => 'Nilphamari Sadar'],
            428 => ['district_id' => 57, 'name' => 'Sadullapur'],
            429 => ['district_id' => 57, 'name' => 'Gaibandha Sadar'],
            430 => ['district_id' => 57, 'name' => 'Palashbari'],
            431 => ['district_id' => 57, 'name' => 'Saghata'],
            432 => ['district_id' => 57, 'name' => 'Gobindaganj'],
            433 => ['district_id' => 57, 'name' => 'Sundarganj'],
            434 => ['district_id' => 57, 'name' => 'Phulchari'],
            435 => ['district_id' => 58, 'name' => 'Thakurgaon Sadar'],
            436 => ['district_id' => 58, 'name' => 'Pirganj'],
            437 => ['district_id' => 58, 'name' => 'Ranisankail'],
            438 => ['district_id' => 58, 'name' => 'Haripur'],
            439 => ['district_id' => 58, 'name' => 'Baliadangi'],
            440 => ['district_id' => 59, 'name' => 'Rangpur Sadar'],
            441 => ['district_id' => 59, 'name' => 'Gangachara'],
            442 => ['district_id' => 59, 'name' => 'Taraganj'],
            443 => ['district_id' => 59, 'name' => 'Badarganj'],
            444 => ['district_id' => 59, 'name' => 'Mithapukur'],
            445 => ['district_id' => 59, 'name' => 'Pirganj'],
            446 => ['district_id' => 59, 'name' => 'Kaunia'],
            447 => ['district_id' => 59, 'name' => 'Pirgacha'],
            448 => ['district_id' => 60, 'name' => 'Kurigram Sadar'],
            449 => ['district_id' => 60, 'name' => 'Nageshwari'],
            450 => ['district_id' => 60, 'name' => 'Bhurungamari'],
            451 => ['district_id' => 60, 'name' => 'Phulbari'],
            452 => ['district_id' => 60, 'name' => 'Rajarhat'],
            453 => ['district_id' => 60, 'name' => 'Ulipur'],
            454 => ['district_id' => 60, 'name' => 'Chilmari'],
            455 => ['district_id' => 60, 'name' => 'Rowmari'],
            456 => ['district_id' => 60, 'name' => 'Char Rajibpur'],
            457 => ['district_id' => 61, 'name' => 'Sherpur Sadar'],
            458 => ['district_id' => 61, 'name' => 'Nalitabari'],
            459 => ['district_id' => 61, 'name' => 'Sreebardi'],
            460 => ['district_id' => 61, 'name' => 'Nakla'],
            461 => ['district_id' => 61, 'name' => 'Jhenaigati'],
            462 => ['district_id' => 62, 'name' => 'Fulbaria'],
            463 => ['district_id' => 62, 'name' => 'Trishal'],
            464 => ['district_id' => 62, 'name' => 'Bhaluka'],
            465 => ['district_id' => 62, 'name' => 'Muktagacha'],
            466 => ['district_id' => 62, 'name' => 'Mymensingh Sadar'],
            467 => ['district_id' => 62, 'name' => 'Dhobaura'],
            468 => ['district_id' => 62, 'name' => 'Phulpur'],
            469 => ['district_id' => 62, 'name' => 'Haluaghat'],
            470 => ['district_id' => 62, 'name' => 'Gouripur'],
            471 => ['district_id' => 62, 'name' => 'Gafargaon'],
            472 => ['district_id' => 62, 'name' => 'Ishwarganj'],
            473 => ['district_id' => 62, 'name' => 'Nandail'],
            474 => ['district_id' => 62, 'name' => 'Tarakanda'],
            475 => ['district_id' => 63, 'name' => 'Jamalpur Sadar'],
            476 => ['district_id' => 63, 'name' => 'Melandaha'],
            477 => ['district_id' => 63, 'name' => 'Islampur'],
            478 => ['district_id' => 63, 'name' => 'Dewanganj'],
            479 => ['district_id' => 63, 'name' => 'Sarishabari'],
            480 => ['district_id' => 63, 'name' => 'Madarganj'],
            481 => ['district_id' => 63, 'name' => 'Bakshiganj'],
            482 => ['district_id' => 64, 'name' => 'Barhatta'],
            483 => ['district_id' => 64, 'name' => 'Durgapur'],
            484 => ['district_id' => 64, 'name' => 'Kendua'],
            485 => ['district_id' => 64, 'name' => 'Atpara'],
            486 => ['district_id' => 64, 'name' => 'Madan'],
            487 => ['district_id' => 64, 'name' => 'Khaliajuri'],
            488 => ['district_id' => 64, 'name' => 'Kalmakanda'],
            489 => ['district_id' => 64, 'name' => 'Mohanganj'],
            490 => ['district_id' => 64, 'name' => 'Purbadhala'],
            491 => ['district_id' => 64, 'name' => 'Netrokona Sadar'],
            492 => ['district_id' => 39, 'name' => 'Madhyanagar'],
            493 => ['district_id' => 38, 'name' => 'Shayestaganj'],
            494 => ['district_id' => 32, 'name' => 'Indurkani'],
            495 => ['district_id' => 50, 'name' => 'Dasar'],
            496 => ['district_id' => 15, 'name' => 'Motihar'],
            497 => ['district_id' => 15, 'name' => 'Shah Makhdum'],
            498 => ['district_id' => 15, 'name' => 'Boalia'],
            499 => ['district_id' => 15, 'name' => 'Rajpara'],
            500 => ['district_id' => 36, 'name' => 'Shah Paran'],
            501 => ['district_id' => 36, 'name' => 'South Surma'],
            502 => ['district_id' => 36, 'name' => 'Moglabazar'],
            503 => ['district_id' => 36, 'name' => 'Jalalabad'],
            504 => ['district_id' => 36, 'name' => 'Bimanbandar'],
            505 => ['district_id' => 27, 'name' => 'Kotwali'],
            506 => ['district_id' => 27, 'name' => 'Khalishpur'],
            507 => ['district_id' => 27, 'name' => 'Sonadanga'],
            508 => ['district_id' => 27, 'name' => 'Daulatpur'],
            509 => ['district_id' => 27, 'name' => 'Khan Jahan Ali'],
            510 => ['district_id' => 59, 'name' => 'Kawnia'],
            511 => ['district_id' => 8, 'name' => 'Bimanbandar'],
            512 => ['district_id' => 8, 'name' => 'Kazirhat'],
            513 => ['district_id' => 8, 'name' => 'Kotwali'],
            514 => ['district_id' => 8, 'name' => 'Sadarghat'],
            515 => ['district_id' => 8, 'name' => 'Patenga'],
            516 => ['district_id' => 8, 'name' => 'Panchlaish'],
            517 => ['district_id' => 8, 'name' => 'Pahartali'],
            518 => ['district_id' => 8, 'name' => 'Khulshi'],
            519 => ['district_id' => 8, 'name' => 'Halishahar'],
            520 => ['district_id' => 8, 'name' => 'Double Mooring'],
            521 => ['district_id' => 8, 'name' => 'Chittagong Kotwali'],
            522 => ['district_id' => 8, 'name' => 'Chawkbazar'],
            523 => ['district_id' => 8, 'name' => 'Chandgaon'],
            524 => ['district_id' => 8, 'name' => 'Bhujpur'],
            525 => ['district_id' => 8, 'name' => 'Bandar'],
            526 => ['district_id' => 8, 'name' => 'Bakolia'],
            527 => ['district_id' => 8, 'name' => 'Bayezid'],
            528 => ['district_id' => 8, 'name' => 'Akbar Shah'],
            529 => ['district_id' => 47, 'name' => 'Wari'],
            530 => ['district_id' => 47, 'name' => 'Vatara'],
            531 => ['district_id' => 47, 'name' => 'Bhashantek'],
            532 => ['district_id' => 47, 'name' => 'Uttar Khan'],
            533 => ['district_id' => 47, 'name' => 'Uttara West'],
            534 => ['district_id' => 47, 'name' => 'Uttara East'],
            535 => ['district_id' => 47, 'name' => 'Turag'],
            536 => ['district_id' => 47, 'name' => 'Tejgaon'],
            537 => ['district_id' => 47, 'name' => 'Tejgaon Industrial'],
            538 => ['district_id' => 47, 'name' => 'Sher-e-Bangla Nagar'],
            539 => ['district_id' => 47, 'name' => 'Shyampur'],
            540 => ['district_id' => 47, 'name' => 'Sutrapur'],
            541 => ['district_id' => 47, 'name' => 'Shahjahanpur'],
            542 => ['district_id' => 47, 'name' => 'Shahbagh'],
            543 => ['district_id' => 47, 'name' => 'Shah Ali'],
            544 => ['district_id' => 47, 'name' => 'Sabujbagh'],
            545 => ['district_id' => 47, 'name' => 'Rupnagar'],
            546 => ['district_id' => 47, 'name' => 'Rampura'],
            547 => ['district_id' => 47, 'name' => 'Ramna'],
            548 => ['district_id' => 47, 'name' => 'Paltan'],
            549 => ['district_id' => 47, 'name' => 'Pallabi'],
            550 => ['district_id' => 47, 'name' => 'New Market'],
            551 => ['district_id' => 47, 'name' => 'Mugda'],
            552 => ['district_id' => 47, 'name' => 'Motijheel'],
            553 => ['district_id' => 47, 'name' => 'Mohammadpur'],
            554 => ['district_id' => 47, 'name' => 'Mirpur Model'],
            555 => ['district_id' => 47, 'name' => 'Lalbagh'],
            556 => ['district_id' => 47, 'name' => 'Kotwali'],
            557 => ['district_id' => 47, 'name' => 'Kadamtali'],
            558 => ['district_id' => 47, 'name' => 'Khilkhet'],
            559 => ['district_id' => 47, 'name' => 'Khilgaon'],
            560 => ['district_id' => 47, 'name' => 'Kamrangirchar'],
            561 => ['district_id' => 47, 'name' => 'Kalabagan'],
            562 => ['district_id' => 47, 'name' => 'Kafrul'],
            563 => ['district_id' => 47, 'name' => 'Jatrabari'],
            564 => ['district_id' => 47, 'name' => 'Hazaribagh'],
            565 => ['district_id' => 47, 'name' => 'Gulshan'],
            566 => ['district_id' => 47, 'name' => 'Gandaria'],
            567 => ['district_id' => 47, 'name' => 'Dhanmondi'],
            568 => ['district_id' => 47, 'name' => 'Demra'],
            569 => ['district_id' => 47, 'name' => 'Darus Salam'],
            570 => ['district_id' => 47, 'name' => 'Dakshin Khan'],
            571 => ['district_id' => 47, 'name' => 'Chawkbazar'],
            572 => ['district_id' => 47, 'name' => 'Cantonment'],
            573 => ['district_id' => 47, 'name' => 'Bimanbandar'],
            574 => ['district_id' => 47, 'name' => 'Bangshal'],
            575 => ['district_id' => 47, 'name' => 'Banani'],
            576 => ['district_id' => 47, 'name' => 'Badda'],
            577 => ['district_id' => 47, 'name' => 'Adabor'],

        ];
    }
}
