name: Force Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH commands on Hostinger
        uses: appleboy/ssh-action@master
        with:
          host: 145.79.212.19
          port: 65002
          username: u881397359
          password: NJnaeem11.
          script: |
            cd /home/u881397359/domains/nenobet.live/public_html
            git pull origin main
            php artisan tinker --execute="Schema::dropIfExists('semester_results'); DB::table('migrations')->where('migration', 'like', '%create_semester_results_table%')->delete();"
            php artisan migrate --force
            npm install
            npm run build
